---
# Docker options
docker_version: '17.09.0~ce-0~ubuntu'
docker_apt_release_channel: 'stable'
docker_apt_repository: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'

# Add users to Docker group
docker_group_members: 
  - 'ubuntu'
  
# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.26.0"
docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
docker_compose_path: /usr/local/bin/docker-compose
