kind: Service
apiVersion: v1
metadata:
  name: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: web