kind: Service
apiVersion: v1
metadata:
  name: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: web