apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ default "" .Values.secrets.password | b64enc | quote }}
