replicaCount: 3

image:
  repository: trnsprntt/current_time_app
  pullPolicy: Always #IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  exposed_port: 5000
  workdir: /home/python_app/

imagePullSecrets: []
nameOverride: "python-app"
fullnameOverride: "python-app-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "pythonapp"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 5000
  name: python-app-service

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

secrets:
  name: lab-11-password
  password: super-secret-lab-11-password

env:
  secretName:
    bonus-secret
  secretVariables:
    ENV_VAR1: var1
    ENV_VAR2: var2
    ENV_VAR3: var3

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

statefulSet:
  volumeClaimTemplates:
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 512M
  podManagementPolicy: "Parallel"

