---
- name: Check the directory is present
  become: true
  file:
    path: "{{ deploy_image_app_folder }}"
    state: directory
    mode: 0755

- name: Copy docker-compose
  template:
    src: template/docker-compose.yml.j2
    dest: "{{ deploy_image_app_folder }}/docker-compose.yaml"
    mode: 0644

- name: Run application
  become: true
  community.docker.docker_compose:
    project_src: "{{ deploy_image_app_folder }}"
    recreate: always
    state: present
    pull: true
    